- hosts: localhost
  connection: local

  vars:
    proxmox_api_user: "root@pam"
    proxmox_api_token_id: "ansible2"
    proxmox_api_token_secret: "5c3de81c-c090-4a80-865b-8ce59920a4f3"
    proxmox_api_host: "10.24.37.4"

  tasks:
    - name: Remove container if exists
      community.general.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        api_host: "{{ proxmox_api_host }}"
        node: "PVE03"
        vmid: 602
        state: absent
      ignore_errors: yes

    - name: Clone container via SSH
      shell: ssh root@10.24.37.4 "pct clone 600 603 --hostname wp2"

    - name: Start container via SSH
      shell: ssh root@10.24.37.4 "pct start 603"